function ExportButton({ quote, discount = 0, currency = 'INR' }) {
  if (!quote) return null;

  const extractPrice = (priceStr) => {
    const match = priceStr.match(/[\d,]+/);
    return match ? parseInt(match[0].replace(/,/g, '')) : 0;
  };

  const totalOriginal = extractPrice(quote.totalCost);
  const discountAmount = (totalOriginal * discount) / 100;
  const finalTotal = totalOriginal - discountAmount;

  const convertCurrency = (amount) => {
    const rates = { INR: 1, USD: 0.012, EUR: 0.011 };
    const symbols = { INR: '₹', USD: '$', EUR: '€' };
    const converted = amount * rates[currency];
    return `${symbols[currency]}${converted.toLocaleString()}`;
  };

  const exportToPDF = () => {
    const content = `
PROFESSIONAL QUOTATION
${quote.projectTitle}

Client Requirements:
${quote.clientRequirementSummary}

Services Breakdown:
${quote.services.map(service => 
  `• ${service.name}: ${convertCurrency(extractPrice(service.price))}
    ${service.description}`
).join('\n\n')}

Summary:
Estimated Duration: ${quote.estimatedDuration}
Subtotal: ${convertCurrency(totalOriginal)}
${discount > 0 ? `Discount (${discount}%): -${convertCurrency(discountAmount)}\n` : ''}Total Cost: ${convertCurrency(finalTotal)}

${quote.notes ? `Notes: ${quote.notes}` : ''}

Generated by QuotationAI
    `;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `quotation-${quote.projectTitle.toLowerCase().replace(/\s+/g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const copyToClipboard = async () => {
    const content = `${quote.projectTitle}\n\n${quote.clientRequirementSummary}\n\nTotal: ${convertCurrency(finalTotal)}\nDuration: ${quote.estimatedDuration}`;
    
    try {
      await navigator.clipboard.writeText(content);
      alert('Quotation copied to clipboard!');
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  return (
    <div className="flex gap-3 mt-6">
      <button
        onClick={exportToPDF}
        className="flex-1 bg-gradient-to-r from-red-500 to-red-600 text-white py-2 px-4 rounded-lg font-medium hover:from-red-600 hover:to-red-700 transition-all shadow-lg"
      >
        📄 Export as Text
      </button>
      <button
        onClick={copyToClipboard}
        className="flex-1 bg-gradient-to-r from-orange-500 to-red-500 text-white py-2 px-4 rounded-lg font-medium hover:from-orange-600 hover:to-red-600 transition-all shadow-lg"
      >
        📋 Copy Summary
      </button>
    </div>
  );
}

export default ExportButton;